'''Imprima a quantidade mínima de notas e moedas necessárias para trocar o valor inicial, 
conforme exemplo fornecido.
Obs: Utilize ponto (.) para separar a parte decimal.'''

x = float(input()) 

print('NOTAS:')
divisao_por_cem = int(x // 100) 
print(str(divisao_por_cem) + ' nota(s) de R$ 100.00') 
x = x - (divisao_por_cem * 100) 
divisao_por_cinquenta = int(x // 50) 
print(str(divisao_por_cinquenta) + ' nota(s) de R$ 50.00')
x = x - (divisao_por_cinquenta * 50) 
divisao_por_vintecinco = int(x // 20) 
print(str(divisao_por_vintecinco) + ' nota(s) de R$ 20.00')
x = x - (divisao_por_vintecinco * 20)
divisao_por_dez = int(x // 10)
print(str(divisao_por_dez) + ' nota(s) de R$ 10.00')
x = x - (divisao_por_dez * 10)
divisao_por_cinco = int(x // 5)
print(str(divisao_por_cinco) + ' nota(s) de R$ 5.00')
x = x - (divisao_por_cinco * 5)
divisao_por_dois = int(x // 2)
print(str(divisao_por_dois) + ' nota(s) de R$ 2.00')

print('MOEDAS:')
x = x - (divisao_por_dois * 2)
divisao_por_um = int(x // 1)
print(str(divisao_por_um) + ' moeda(s) de R$ 1.00')
x = x - (divisao_por_um)
divisao_por_05 = int(x // 0.5)
print(str(divisao_por_05) + ' moeda(s) de R$ 0.50')
x = x - (divisao_por_05 * 0.5)
divisao_por_025 = int(x // 0.25)
print(str(divisao_por_025) + ' moeda(s) de R$ 0.25')
x = x - (divisao_por_025 * 0.25)
divisao_por_010 = int(x // 0.10)
print(str(divisao_por_010) + ' moeda(s) de R$ 0.10')
x = x - (divisao_por_010 * 0.10)
divisao_por_005 = int(x // 0.05)
print(str(divisao_por_005) + ' moeda(s) de R$ 0.05')
x = x - (divisao_por_005 * 0.05) + 0.0099
divisao_por_001 = int(x // 0.01)
print(str(divisao_por_001) + ' moeda(s) de R$ 0.01')